### ISSUE TITLE
Fix schedule box

### ISSUE THREAD

**Issue by 0NotApplicable0** [DangItJason/TutorBase#13]
When trying to create a new schedule the box get bugged not, I'm not sure why. There is some strange looking boxes and the calendar boxes don't work. 

Looks like this:
![wack](https://cdn.discordapp.com/attachments/690602287873130618/762478755985096704/unknown.png)

Should look like this:
![lookLikeThis](https://cdn.discordapp.com/attachments/690602287873130618/762479228687482950/unknown.png)

**Comment by 0NotApplicable0** [comment]
We also want to format this box so it fits the mobile view, currently it doesn't, see below.

![image](https://user-images.githubusercontent.com/32582432/95616760-570f5100-0a38-11eb-8e16-1b9505086ab8.png)

**Comment by UnitedBagels** [comment]
Extended issue to Toast UI repository: https://github.com/nhn/tui.calendar/issues/707

**Comment by UnitedBagels** [comment]
Solved
