### ISSUE TITLE
Build a Card component to represent Previous/Upcoming/Completed meetings

### ISSUE THREAD

**Issue by jakezam** [DangItJason/TutorBase#24]
Build a component that will display information for a particular meeting, categorized by color as:

- Pending(Orange)
- Upcoming(Blue)
- Completed(Green)
- Denied(Red)

The card will expand on click to reveal more information

The Pending card will show a check/x mark to either accept or deny the meeting

**Comment by jakezam** [comment]
Card UI Example:

![image](https://user-images.githubusercontent.com/44008726/97364632-b5329580-187a-11eb-86d0-a1cc41a2f8f8.png)

**Comment by DangItJason** [comment]
The inside (expandable) of the card needs to be finished and this issue can be closed
