### ISSUE TITLE
Implement routes for accept/reject marks

### ISSUE THREAD

**Issue by DangItJason** [DangItJason/TutorBase#33]
Per title ... Inside the meetings tab, the accept and reject marks needs to be implemented. This would either move the appointment to an "Upcoming" or "Denied" color.

![image](https://user-images.githubusercontent.com/46536008/98026320-f1b14480-1dd8-11eb-89ac-c2deb809185e.png)

**Comment by cjreed121** [comment]
Is this still open? Also what branch?

**Comment by DangItJason** [comment]
Yes it's still open.

client-meetings branch.
