### ISSUE TITLE
Schedule Availability in Tutor Operations

### ISSUE THREAD

**Issue by cjreed121** [DangItJason/TutorBase#36]
When a tutor goes to edit or see their availability, I'm not sure exactly what format that should be. I know it was proposed of just doing text for those but a more of a graphical UI like the one used for scheduling the meeting could look nice there.

**Comment by jweiss0** [comment]
The plan was to use [this](https://github.com/nhn/toast-ui.react-calendar) component to allow a tutor to select hours available to work during the day. Once selected, available hours will be displayed as the following:

![image](https://user-images.githubusercontent.com/18493608/98755966-96162680-2397-11eb-81ad-ebac9c6960c2.png)

**Comment by jweiss0** [comment]
Note that a tutor's availability for a certain time of day is stored as an array, e.g. [600, 800] represents availability to work from 6:00AM to 8:00AM. Call this a "time block". Furthermore, a tutor's weekly availability is stored as an array of 7 elements, where each element stores availability for a day of the week (Sunday - Saturday). Each of these slots for a day of the week stores an array of time blocks. 
For example, the weekly availability for the above user will look like the following:
[
  [[600,800], [1600, 2000]],
  [[700,900], [1600, 2000]],
  [[1600, 2000]],
  [[1600, 2000]],
  [[1600, 2000]],
  [[1600, 2000]],
  [[1600, 2000]]
]
