### ISSUE TITLE
Main Login Screen

### ISSUE THREAD

**Issue by DangItJason** [DangItJason/TutorBase#38]
Main Login Screen - Elements are overlapping over each other. 

1. Arrange elements so they do not over lap.
or
2. Create own design.

![image](https://user-images.githubusercontent.com/46536008/99481812-e7d72780-2928-11eb-8b62-f0163f74c083.png)

**Comment by cjreed121** [comment]
I fixed issue in tutor operations. I was thinking about a potential redesign though. I was thinking maybe it could just be an overlay on the landing page. Thoughts?

**Comment by UnitedBagels** [comment]
I'm going to attempt a redesign for this on tutor-operations, just to get an idea of what it might look like.
