### ISSUE TITLE
Sidebar tabs move user to home page

### ISSUE THREAD

**Issue by DangItJason** [DangItJason/TutorBase#50]
None of the sidebar tabs move the user the appropriate page. 

For example, the settings tab will not move the user to the settings page BUT instead the home page.

Enable each button to move the user to the appropriate page.

**Comment by jweiss0** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Sidebar tabs move user to home page](https://trello.com/c/lGpv5K9X/23-sidebar-tabs-move-user-to-home-page)

**Comment by jweiss0** [comment]
This only happens for pages that have not yet been created and linked accordingly in the Panel file. Closing, since this issue will solve itself once all pages are implemented (Meetings, History, Settings).
